version: "3"

services:
  jasmin_sms_configurer:
    build: .
    image: gluontech/jasmin_sms_configurer
    restart: unless-stopped
    environment:
      - ENDPOINT=${ENDPOINT}
      - TIMEOUT=180
      - AMPQ_HOST=${ENDPOINT_IP}
      - AMPQ_PORT=${AMPQ_PORT}
      - AMPQ_USERNAME=${AMPQ_USERNAME}
      - AMPQ_PASSWORD=${AMPQ_PASSWORD}

  jasmin_sms_redis:
    image: redis:alpine
    restart: unless-stopped

  jasmin_sms_amq:
    image: rabbitmq:alpine
    restart: unless-stopped

  jasmin_sms_jasmin:
    image: jookies/jasmin:latest
    restart: unless-stopped
    container_name: jasmin
    ports:
      - 2775:2775
      - 8990:8990
      - 1401:1401
    depends_on:
      - jasmin_sms_redis
      - jasmin_sms_amq
    environment:
      REDIS_CLIENT_HOST: jasmin_sms_redis
      AMQP_BROKER_HOST: jasmin_sms_amq