version: "3"

services:
#  jasmin_sms_configurer:
#    build: .
#    image: gluontech/jasmin_sms_configurer
#    restart: unless-stopped
#    environment:
#      - AMPQ_HOST=${AMPQ_HOST}
#      - AMPQ_VHOST=${AMPQ_VHOST}
#      - AMPQ_PORT=${AMPQ_PORT}
#      - AMPQ_USERNAME=${AMPQ_USERNAME}
#      - AMPQ_PASSWORD=${AMPQ_PASSWORD}
#      - AMPQ_QUEUE_NAME=${AMPQ_QUEUE_NAME}
#      - AMPQ_EXCHANGE_NAME=${AMPQ_EXCHANGE_NAME}

  jasmin_sms_redis:
    image: redis:alpine
    restart: unless-stopped

  jasmin_sms_amq:
    image: rabbitmq:alpine
    restart: unless-stopped

  jasmin_sms_jasmin:
    image: jookies/jasmin:latest
    restart: unless-stopped
    container_name: jasmin
    ports:
      - 2775:2775
      - 8990:8990
      - 1401:1401
    depends_on:
      - jasmin_sms_redis
      - jasmin_sms_amq
    environment:
      REDIS_CLIENT_HOST: jasmin_sms_redis
      AMQP_BROKER_HOST: jasmin_sms_amq

  jasmin_sms_server_ampq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672